    
sensor:  
  - platform: mqtt
    state_topic: "multisensor/bedroom"
    name: "Bedroom Multisensor"
    json_attributes:
      - humidity
      - motion
      - temperature
      - heatIndex

automations:
  - id: turn_on_bedroom_at_night_when_movement
    alias: Turn On Bedroom At Night When Movement
    trigger:
      platform: mqtt
      topic: multisensor/bedroom
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ is_state_attr("sensor.bedroom_multisensor", "motion", "ON") }}'   
        - condition: sun
          after: sunset
          after_offset: '-00:30:00'
        - condition: time
          before: '21:00:00'